spring:
  datasource:
    username: thesis
    password: thesis
    url: jdbc:postgresql://localhost:5432/account-service
  jpa:
    show-sql: true
    properties:
      default_schema: thesis
      hibernate:
        hbm2ddl:
          auto: update
        jdbc:
            lob:
              non_contextual_creation: true
              
logging:
  level:
    org:
      hibernate:
        sql: debug
        starttls:
          enabled: true
          required: true
        
server:
  port: 8084

  