server:
  port: 8088
  
spring:
  datasource:
    username: thesis
    password: thesis
    url: jdbc:postgresql://localhost:5432/chat-service
  jpa:
    show-sql: true
    properties:
      default_schema: thesis
      hibernate:
        hbm2ddl:
          auto: update
        jdbc:
            lob:
              non_contextual_creation: true
logging:
  level:
    org:
      hibernate:
        sql: debug