server:
  port: 8081

spring:
  datasource:
    username: thesis
    password: thesis
    url: jdbc:postgresql://localhost:5432/project-service

  jpa:
    properties: 
        default_schema: thesis
        hibernate:
          hbm2ddl:
            auto: update
          jdbc:
            lob:
              non_contextual_creation: true
    show-sql: true    
logging:
  level:
    org:
      hibernate:
        sql:  debug
        
        